name: benchmark.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start the API
        run: npm run start

      - name: Wait for the API
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:3000/work

      - name: Execute benchmark
        run: npm run autocannon
