name: load-tests-compare.yml
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  load-test-compare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start the API as a single worker
        run: nohup npm run start-single &

      - name: Save PID
        run: echo $! > save_pid.txt

      - name: Wait for the API
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: http://localhost:3000/work

      - name: Execute load tests
        run: npx artillery run tests/demo_api_load.yml

      - name: Kill API
        run: kill -9 `cat save_pid.txt`
